{'timestamp': '2023-08-04T21:59:37.526263', 'remitent': 'API Thread', 'output': ('5PcGtT_m7yn-6oYCAAAB', '1-emd-2563y0', '1', 'hows it oing')}
 
{'timestamp': '2023-08-04T21:59:56.469793', 'remitent': 'API Thread', 'output': ('5PcGtT_m7yn-6oYCAAAB', '1-emd-2563y0', '1', 'what time its
')}
 
{'timestamp': '2023-08-04T21:59:57.267937', 'remitent': 'GPT', 'output': {'name': 'date_clock', 'arguments': '{}'}}
 
{'timestamp': '2023-08-04T21:59:57.269718', 'remitent': 'IO ROUTER', 'output': {'module': 'task_msc', 'args_key': 'args', 'arguments': '2', 'required_lvl': 0, 'key': 'date_clock'}}
 
{'timestamp': '2023-08-04T21:59:57.271550', 'remitent': 'COMMAND ROUTER', 'output': (<class 'dict'>, {'module': 'task_msc', 'args_key': 'args', 'arguments': '2', 'required_lvl': 0, 'key': 'date_clock'}, <class 'dict'>, {})}
 
{'timestamp': '2023-08-04T21:59:57.272016', 'remitent': 'COMMAND ROUTER', 'output': ['trying to execute date_clock with args = 2. Session: 5PcGtT_m7yn-6oYCAAAB ']}
 
{'timestamp': '2023-08-04T21:59:57.272760', 'remitent': 'COMMAND ROUTER', 'output': (True, ('2023-08-04 21:59:57', datetime.date(2023, 8, 4), '21:59:57'))}
 
{'timestamp': '2023-08-04T21:59:57.273122', 'remitent': 'COMMAND ROUTER', 'output': ('date_clock has been executed', 'args = 2', '5PcGtT_m7yn-6oYCAAAB')}
 
{'timestamp': '2023-08-04T21:59:57.273886', 'remitent': 'API Thread', 'output': (TypeError('Object of type date is not JSON serializable'), 'Traceback (most recent call last):
  File "/workspaces/Emma-ServerSide/emma/services/API/user_io/app.py", line 131, in process_responses
    self.socketio.emit("response", data, room=session_id)
  File "/opt/conda/envs/Emma/lib/python3.9/site-packages/flask_socketio/__init__.py", line 462, in emit
    self.server.emit(event, *args, namespace=namespace, to=to,
  File "/opt/conda/envs/Emma/lib/python3.9/site-packages/socketio/server.py", line 319, in emit
    self.manager.emit(event, data, namespace, room=room,
  File "/opt/conda/envs/Emma/lib/python3.9/site-packages/socketio/base_manager.py", line 172, in emit
    self.server._emit_internal(eio_sid, event, data, namespace, id)
  File "/opt/conda/envs/Emma/lib/python3.9/site-packages/socketio/server.py", line 646, in _emit_internal
    self._send_packet(eio_sid, self.packet_class(
  File "/opt/conda/envs/Emma/lib/python3.9/site-packages/socketio/server.py", line 651, in _send_packet
    encoded_packet = pkt.encode()
  File "/opt/conda/envs/Emma/lib/python3.9/site-packages/socketio/packet.py", line 64, in encode
    encoded_packet += self.json.dumps(data, separators=(\',\', \':\'))
  File "/opt/conda/envs/Emma/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/opt/conda/envs/Emma/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/conda/envs/Emma/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/conda/envs/Emma/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f\'Object of type {o.__class__.__name__} \'
TypeError: Object of type date is not JSON serializable
')}
 
{'timestamp': '2023-08-04T22:01:10.044748', 'remitent': 'API Thread', 'output': ('5PcGtT_m7yn-6oYCAAAB', '1-emd-2563y0', '1', 'stop the app')}
 
{'timestamp': '2023-08-04T22:01:10.848395', 'remitent': 'GPT', 'output': {'name': 'server_shutdown', 'arguments': '{}'}}
 
{'timestamp': '2023-08-04T22:01:10.849172', 'remitent': 'IO ROUTER', 'output': {'module': 'sys_v', 'args_key': 'None', 'required_lvl': 1, 'key': 'server_shutdown'}}
 
{'timestamp': '2023-08-04T22:01:10.849893', 'remitent': 'COMMAND ROUTER', 'output': (<class 'dict'>, {'module': 'sys_v', 'args_key': 'None', 'required_lvl': 1, 'key': 'server_shutdown'}, <class 'dict'>, {})}
 
{'timestamp': '2023-08-04T22:01:10.851576', 'remitent': 'COMMAND ROUTER', 'output': ['trying to execute server_shutdown with args = None. Session: 5PcGtT_m7yn-6oYCAAAB ']}
 
{'timestamp': '2023-08-04T22:01:10.853298', 'remitent': 'LOGGER', 'output': 'Handling shutdown...'}
 
